### ISSUE TITLE
2.1 release missing?

### ISSUE THREAD

**Issue by anarcat** [atheme/libmowgli-2#36]
there's something strange in libmowgli... there are a bunch of commits since the last release (2.0.0?) that have not been released as a tag. yet the atheme package mentions using mowgli 2.1 in some commitlogs, and in fact, the API changed.. see for example https://github.com/atheme/atheme/commit/3b5a1784be4bcab706706837a2298a3273367556

could we get a release of libmowgli - otherwise how are we supposed to build atheme?

**Comment by anarcat** [comment]
ping?

**Comment by maxteufel** [comment]
https://github.com/atheme/libmowgli-2/releases/tag/v2.1.0

**Comment by anarcat** [comment]
thanks
